[project]
name = "2026-season"
version = "0.1.0"
description = "BCR 4504 Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robotpy[all]>=2025.3.2.2",
    "numpy",
    "opencv-python"
]

