name: Lint

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruff lint (check)
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."

      - name: Ruff format (verify only)
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
